spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    name: tools
    username: root
    password: ZNZLkj2020
    url: jdbc:mysql://124.70.72.160:3306/tools?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=15000&allowMultiQueries=true&useSSL=false
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: ExpendHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的bean的时候，是否允许覆盖注册到容器
  thymeleaf:
    cache: false
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    locale: zh_CN
  freemarker:
    cache: false
    charset: utf-8
    suffix: .ftl
    # redis 配置
  redis:
    # 地址
    host: 124.70.72.160
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
#此配置开启mybatis sql打印
logging:
  level:
    com:
      springboot:
        tools:
          mapper: debug
mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
web:
  anon-url: /actuator/**,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/login,/logout,/captchaImage
captcha:
  # 验证码类型 math 数组计算 char 字符验证
  type: math